# Classifying emotions from model RoBERTa

## __Initializing model__

### __Model trained on GoEmotions (Dataset from Google)__

__What emotions are we talking about ?__

admiration, amusement, anger, annoyance, approval, caring, 
confusion, curiosity, desire, disappointment, disapproval, 
disgust, embarrassment, excitement, fear, gratitude, grief, 
joy, love, nervousness, optimism, pride, realization, relief, 
remorse, sadness, surprise + neutral

In [4]:
# Imports
from transformers import pipeline
import pandas as pd

In [ ]:
# Initializing model
emotion_classifier_go = pipeline(
    'text-classification',
    model='SamLowe/roberta-base-go_emotions',
    top_k=4
)

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: SamLowe/roberta-base-go_emotions
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [10]:
# Trying it out

response = emotion_classifier_go("I watched him go with a sinking feeling in my stomach")
pd.DataFrame(response[0])

            label     score
0         sadness  0.585110
1  disappointment  0.106088
2     nervousness  0.099693
3            fear  0.080609

### __Alternative model__

__What emotions are we talking about ?__

anger 🤬, disgust 🤢, fear 😨, joy 😀, neutral 😐, sadness 😭, surprise 😲

In [ ]:
# Initializing model

emotion_classifier_simple = pipeline("text-classification",
                      model="j-hartmann/emotion-english-distilroberta-base",
                      top_k=4)

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: j-hartmann/emotion-english-distilroberta-base
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [13]:
# Trying it out

response = emotion_classifier_simple("Wow, this is really beautiful")
pd.DataFrame(response[0])

      label     score
0  surprise  0.960435
1       joy  0.019467
2   neutral  0.008130
3      fear  0.004241